/**
 * \file shared_lib_api.c
 * \brief
 *     Contains implementation for some of the APIs exposed by shared_lib_api.h
 *
 *
 * \copyright
 *  Copyright (c) Qualcomm Innovation Center, Inc. All Rights Reserved.
 *  SPDX-License-Identifier: BSD-3-Clause-Clear
 */

#include "shared_lib_api.h"

#ifdef AVS_BUILD_SOS

/** Including Autogenerated version file containing :
 *
 *    SHARED_LIB_API__BUILD_TOOLS_VERSION, SHARED_LIB_API__LIB_MAJOR_VERSION,
 *    SHARED_LIB_API__LIB_MINOR_VERSION,
 *    */
#include "so_version.h"

const shared_lib_build_property_t shared_lib_build_property = {
   SHARED_LIB_API__SHARED_LIB_BUILD_PROPERTY_VERSION, // uint16_t build_property_version;
   SHARED_LIB_API__API_MAJOR_VERSION,                 // uint16_t api_major_version;
   SHARED_LIB_API__API_MINOR_VERSION,                 // uint16_t api_minor_version;
   SHARED_LIB_API__LIB_MAJOR_VERSION,                 // uint16_t lib_major_version;
   SHARED_LIB_API__LIB_MINOR_VERSION,                 // uint16_t lib_minor_version;
   0,                                                 // uint16_t reserved;
   SHARED_LIB_API__BUILD_TOOLS_VERSION,               // uint32_t build_tools_version;
};

const char shared_lib_engineering_build_id[] = ENGG_TIMESTAMP;
const char shared_lib_qualcomm_build_id[]    = QCOM_TIMESTAMP;


const amdb_module_build_ts_info_t spf_build_property_ts_info = {
   SHARED_LIB_BUILD_TS_YEAR,
   SHARED_LIB_BUILD_TS_MONTH,
   SHARED_LIB_BUILD_TS_DAY,
   SHARED_LIB_BUILD_TS_HOUR,
   SHARED_LIB_BUILD_TS_MIN,
   SHARED_LIB_BUILD_TS_SEC,
};


#else // AVS_BUILD_SOS

/** Including Autogenerated version file containing :
 *
 *  contains SHARED_LIB_API__BUILD_TOOLS_VERSION (32 bit num: xx.yy.zz=00xxyyzz)
 *  */
#include "dsp_version.h"

const spf_build_property_t spf_build_property = {
   SHARED_LIB_API__BUILD_PROPERTY_VERSION,   // uint16_t build_property_version;
   SHARED_LIB_API__API_MAJOR_VERSION,             // uint16_t api_major_version;
   SHARED_LIB_API__API_MINOR_VERSION,             // uint16_t api_minor_version;
   (uint32_t)SHARED_LIB_API__BUILD_TOOLS_VERSION, // uint32_t build_tools_version;
};

#endif // AVS_BUILD_SOS
